ThriftshopSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ThriftshopSite.Data;
using ThriftshopSite.Models;


namespace ThriftshopSite.Controllers
{
    [Authorize(Roles = "Employee,Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> FilterByOne(string? name)
        {
            List<CategoryProduct> listProduducts = _context.CategoryProducts.Where(a => a.CategoriesName == name).ToList();
            List<Product> listCategory = new List<Product>();

            foreach (CategoryProduct categoryProduct in listProduducts)
            {
                Product product = await _context.Products.FirstOrDefaultAsync(m => m.Id == categoryProduct.ProductsId);
                listCategory.Add(product);
            }
            var category = await _context.Categories.FirstOrDefaultAsync(m => m.Name == name);
             return PartialView("_partialtest", listCategory);

        }
        /// <summary>
        /// uses a json file to send multiple fitlers these filter will be used to filter the products based on categories
        /// if there are no categories provided it will instead show every product.
        /// </summary>
        /// <param name="categoriesJson"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> FilterByMultiple(string? categoriesJson)
        {
            
            List<string> categories = JsonConvert.DeserializeObject<List<string>>(categoriesJson);

            List<CategoryProduct> listProduducts2 = categories
                .SelectMany(categorie => _context.CategoryProducts.Where(cp => cp.CategoriesName == categorie))
                .ToList();

            List <CategoryProduct> filteredList = listProduducts2
                .GroupBy(x => x.ProductsId)
                .Where(g => categories.All(c => g.Any(x => x.CategoriesName == c)))
    .            Select(g => g.First())
                .ToList();


            List<Product> listProducts = new List<Product>();

            foreach (CategoryProduct categoryProduct in filteredList)
            {
                Product product = await _context.Products.FirstOrDefaultAsync(m => m.Id == categoryProduct.ProductsId);
                listProducts.Add(product);
            }
            if(!categories.Any())
            {
                listProducts = _context.Products.ToList();
            }
            return PartialView("_partialtest", listProducts);

        }

        // GET: Products
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            ViewData["Categories"] = await _context.Categories.ToListAsync();
              return _context.Products != null ? 
                          View(await _context.Products.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Products'  is null.");
        }

        // GET: Products/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            List<FileModel> files = _context.Files.Where(a => a.Product.Id == id).ToList();

            List<CategoryProduct> list2 = _context.CategoryProducts.Where(a => a.ProductsId == id).ToList();
            List<Category> listCategory= new List<Category>();
            foreach (CategoryProduct categoryProduct in list2)
            {
                Category category = await _context.Categories.FirstOrDefaultAsync(m => m.Name == categoryProduct.CategoriesName);
                listCategory.Add(category);
            }
            ViewData["Categories"] = listCategory;
            return View(product);
        }

        // GET: Products/Details/5
        /// <summary>
        /// makes it possible to add a category to the product chosen from a list of categories not yet added to the product
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Add(Guid? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            List<FileModel> files = _context.Files.Where(a => a.Product.Id == id).ToList();

            List<CategoryProduct> list2 = _context.CategoryProducts.Where(a => a.ProductsId == id).ToList();
            List<Category> listCategory = new List<Category>();
            foreach (CategoryProduct categoryProduct in list2)
            {
                Category category = await _context.Categories.FirstOrDefaultAsync(m => m.Name == categoryProduct.CategoriesName);
                listCategory.Add(category);
            }
            ViewData["Categories"] = listCategory;
            return View(product);
        }

        // GET: Products/Create
        /// <summary>
        /// Sends the user to Create products with a guid for the id of product
        /// its also gives a list of thriftshops to the user based on what shops he's a member of
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Create()
        {
            //@User.Identity?.Name
            string userName = User.Identity.Name;
            UserAccount user = await _context.UserAccount.FirstAsync(m => m.Name == userName);

            IEnumerable<ThriftShop> thriftShops = _context.EmployeeThriftShops.Include(x => x.ThriftShop).Where(entry => entry.Account == user).Select(entry => entry.ThriftShop).AsEnumerable<ThriftShop>();
            ViewData["Thrifshop"] = thriftShops;

            ViewData["Categories"] = _context.Categories;
            var Fileid = TempData["ProductsId"];
            //alles ophalen op basis van ditdan toeveogen aanproduct
            // dan updaten zodat je ze kloppen met de goede productid
            // ViewData["ProductsId"] = productslist;

            ViewData["FileList"] = new List<FileModel>();
            Product product = new Product();
            product.Id = Guid.NewGuid();
            ViewData["Product"] = product;
            return View(); 
        }


        /// <summary>
        /// Creates a new product with a thriftshop
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <param name="inventory"></param>
        /// <param name="price"></param>
        /// <param name="description"></param>
        /// <param name="image"></param>
        /// <param name="thriftShop"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Createshop(Guid id, string name, int inventory, double price, string description, string image, string thriftShop)
        {
            //maak van thriftshop een guid dan zelfde doen dan klaar
            if (ModelState.IsValid)
            {
                var thriftShopfull = await _context.ThriftShops.FirstOrDefaultAsync(m => m.Name == thriftShop);
                Product product = new Product(id, name, inventory, price, description, image, thriftShopfull);
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddImageFile(Product product,FileModel fileModel)
        {
            try
            {
                product.Files.Add(fileModel);
                return PartialView("_AllTweets", product);
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// send the player to a view where he can add a category with a list of categories that can be added based on what categories the product already possses.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Products/Create
        public async Task<IActionResult> AddCategory(Guid? id)
        {
            ViewData["ProductId"] = id;
            List<Category> list1 = _context.Categories.ToList();
            List<CategoryProduct> list2 = _context.CategoryProducts.Where(a => a.ProductsId == id).ToList();
            List<Category> list3 = new List<Category>();
            foreach (CategoryProduct categoryProduct in list2)
            {
                Category category = await _context.Categories.FirstOrDefaultAsync(m => m.Name == categoryProduct.CategoriesName);
                list3.Add(category);
            }
            List<Category> list = list1.Except(list3).ToList();
            ViewData["Categories"] =  list;
            return View();

        }
        public async Task<IActionResult> AddImage(Guid? id)
        {
            ViewData["ProductId"] = id;
            return View();

        }
        
        
        /// <summary>
        /// Adds a category to a product based on a existing category chosen from a list and the id of the product.
        /// </summary>

ThriftshopSite/Controllers/ThriftShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThriftshopSite.Data;
using ThriftshopSite.Models;

namespace ThriftshopSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ThriftShopsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ThriftShopsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ThriftShops
        public async Task<IActionResult> Index()
        {
              return _context.ThriftShops != null ? 
                          View(await _context.ThriftShops.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ThriftShops'  is null.");
        }

        // GET: ThriftShops/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.ThriftShops == null)
            {
                return NotFound();
            }

            var thriftShop = await _context.ThriftShops
                .FirstOrDefaultAsync(m => m.Name == id);
            if (thriftShop == null)
            {
                return NotFound();
            }
            ViewData["Products"] = _context.Products.Where(m => m.Shop.Name == id);
            
            return View(thriftShop);
        }

        // GET: ThriftShops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ThriftShops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Location")] ThriftShop thriftShop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(thriftShop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(thriftShop);
        }

        // GET: ThriftShops/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.ThriftShops == null)
            {
                return NotFound();
            }

            var thriftShop = await _context.ThriftShops.FindAsync(id);
            if (thriftShop == null)
            {
                return NotFound();
            }
            return View(thriftShop);
        }

        // POST: ThriftShops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Location")] ThriftShop thriftShop)
        {
            if (id != thriftShop.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(thriftShop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThriftShopExists(thriftShop.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(thriftShop);
        }

        // GET: ThriftShops/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.ThriftShops == null)
            {
                return NotFound();
            }

            var thriftShop = await _context.ThriftShops
                .FirstOrDefaultAsync(m => m.Name == id);
            if (thriftShop == null)
            {
                return NotFound();
            }

            return View(thriftShop);
        }

        // POST: ThriftShops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.ThriftShops == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ThriftShops'  is null.");
            }
            var thriftShop = await _context.ThriftShops.FindAsync(id);
            if (thriftShop != null)
            {
                _context.ThriftShops.Remove(thriftShop);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        private bool ThriftShopExists(string id)
        {
          return (_context.ThriftShops?.Any(e => e.Name == id)).GetValueOrDefault();
        }
    }
}

ThriftshopSite/Views/Shared/_Files.cshtml
@model ThriftshopSite.Models.Product;
@using (Html.BeginForm("Create", "Files"))  
{  
    <div style="height: 300px; width: 600px; overflow-y: auto">  
        <table border="1">  
      
        </table>  
    </div>  
    <input type="submit" value="Save" style="float: right; width: 70px; font-size: 12px" />  
}

ThriftshopSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThriftshopSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThriftshopSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ThriftshopSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul1 class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThriftShops" asp-action="Index">Shops</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="Index">Admin</a>
                            </li>

                        }  
                        @if (User.IsInRole("Employee") || User.IsInRole("Admin"))
                                    {
                         <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAccounts" asp-action="EmployeeAdd">Employee Add</a>
                         </li>
                        }
                                 
                    </ul1>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ThriftshopSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ThriftshopSite/Views/Shared/_partialtest.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<ThriftshopSite.Models.Product>
@{
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inventory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inventory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                <a asp-controller="Products" asp-action="Add" asp-route-id="@item.Id">Add</a>
            </td>
        </tr>
}
    </tbody>
</table>